// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportJSON(arg1, arg2) {
  return window['go']['main']['App']['ExportJSON'](arg1, arg2);
}

export function ExportXML(arg1) {
  return window['go']['main']['App']['ExportXML'](arg1);
}

export function GetCurrentFilePath() {
  return window['go']['main']['App']['GetCurrentFilePath']();
}

export function GetDesign() {
  return window['go']['main']['App']['GetDesign']();
}

export function LoadDesign() {
  return window['go']['main']['App']['LoadDesign']();
}

export function NewDesign() {
  return window['go']['main']['App']['NewDesign']();
}

export function SaveDesign(arg1) {
  return window['go']['main']['App']['SaveDesign'](arg1);
}

export function SaveDesignAs(arg1) {
  return window['go']['main']['App']['SaveDesignAs'](arg1);
}

export function SetDesign(arg1) {
  return window['go']['main']['App']['SetDesign'](arg1);
}

export function ShowConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowConfirmDialog'](arg1, arg2);
}
