// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportJSON():Promise<string>;

export function ExportXML():Promise<string>;

export function GetCurrentFilePath():Promise<string>;

export function GetDesign():Promise<main.GUIDesign>;

export function LoadDesign():Promise<main.GUIDesign>;

export function NewDesign():Promise<main.GUIDesign>;

export function SaveDesign():Promise<string>;

export function SaveDesignAs():Promise<string>;

export function SetDesign(arg1:main.GUIDesign):Promise<void>;
