// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportJSON() {
  return window['go']['main']['App']['ExportJSON']();
}

export function ExportXML() {
  return window['go']['main']['App']['ExportXML']();
}

export function GetDesign() {
  return window['go']['main']['App']['GetDesign']();
}

export function LoadDesign() {
  return window['go']['main']['App']['LoadDesign']();
}

export function NewDesign() {
  return window['go']['main']['App']['NewDesign']();
}

export function SaveDesign() {
  return window['go']['main']['App']['SaveDesign']();
}

export function SetDesign(arg1) {
  return window['go']['main']['App']['SetDesign'](arg1);
}
