// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportJSON(arg1:string,arg2:string):Promise<string>;

export function ExportXML(arg1:string):Promise<string>;

export function GetCurrentFilePath():Promise<string>;

export function GetDesign():Promise<main.GUIDesign>;

export function LoadDesign():Promise<main.GUIDesign>;

export function NewDesign():Promise<main.GUIDesign>;

export function SaveDesign(arg1:string):Promise<string>;

export function SaveDesignAs(arg1:string):Promise<string>;

export function SetDesign(arg1:main.GUIDesign):Promise<void>;

export function ShowConfirmDialog(arg1:string,arg2:string):Promise<boolean>;
